apiVersion: v1
kind: Service
metadata:
  name: w12-charles-wallet
  namespace: dev
  labels:
    app: w12-charles-wallet
    cloudpros.io/lab: week-12
    cloudpros.io/student: charles
spec:
  type: ClusterIP
  selector:
    app: w12-charles-wallet
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80